---
name: chat_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  shared_preferences: ^2.0.18
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/coding.png"

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
